version: "3"

services:
  test:
    build:
      context: .
      dockerfile: dev.Dockerfile
      target: develop-img
    volumes:
      - ./:/app
    networks:
      - sail
  test-nginx:
    build:
      context: .
      dockerfile: dev.Dockerfile
      target: nginx-img
    ports:
      - 5000:80
    volumes:
      - ./nginx/dev.conf:/etc/nginx/conf.d/default.conf
    networks:
      - sail
networks:
  sail: 
    driver: bridge