version: "3"

services:
  test:
    build:
      context: .
      dockerfile: Dockerfile
      target: production
    volumes:
      - ./:/app
    networks:
      - sail
  test-nginx:
    build:
      context: .
      dockerfile: Dockerfile
      target: nginx-img
    ports:
      - 80:80
    volumes:
      - ./nginx/master.conf:/etc/nginx/conf.d/default.conf
    networks:
      - sail
networks:
  sail: 
    driver: bridge

